from pydantic import BaseModel
from typing import Optional

class ChatRequest(BaseModel):
    user_id: str  # 🆕 Add this field to identify the user/session
    file_id: str  # Existing field (used to locate the uploaded CSV)
    query: str    # The user's natural language query

class ChatResponse(BaseModel):
    code: str  # The Python code generated by the model

class FeedbackRequest(BaseModel):
    query: str  # User session ID
    code: str   # The generated code to which feedback applies
    feedback: Optional[str] = None  # 'thumbs_up', 'thumbs_down', or None